/// Golden tests for `coreml_mrope.dart`.
///
/// Goldens generated by `/tmp/opencode/gen_rope_goldens.py` using a verbatim
/// port of HuggingFace `get_rope_index` from
/// `models--PaddlePaddle--PaddleOCR-VL-1.5/.../modeling_paddleocr_vl.py`.
/// Re-run that script (with `.venv/bin/python`) and paste the output below if
/// the HF reference ever changes.
///
/// Each case is a real `[3, 1, S]` position-id tensor flattened row-major:
///   `[t_0…t_{S-1}, h_0…h_{S-1}, w_0…w_{S-1}]`.
library;

import 'package:dart_inference/src/models/paddle_ocr_vl/coreml_mrope.dart';
import 'package:test/test.dart';

const _imageTokenId = 100295;

void main() {
  group('computeMRopePositionIds — HF goldens', () {
    test('tiny_2x2_grid: text + 4-token image span + trailing text', () {
      // Grid (1,4,4) → llm (1,2,2) → 4 image placeholders.
      final inputIds = <int>[
        10, 11, // pre-text
        101305, // VISION_START (treated as pre-text by HF)
        _imageTokenId, _imageTokenId, _imageTokenId, _imageTokenId,
        101306, // VISION_END (treated as trailing text by HF)
        20, 21, 22, // trailing text
      ];
      final got = computeMRopePositionIds(
        inputIds: inputIds,
        imageGridThw: (1, 4, 4),
        imageTokenId: _imageTokenId,
      );
      const expected = <double>[
        0, 1, 2, 3, 3, 3, 3, 5, 6, 7, 8, // t
        0, 1, 2, 3, 3, 4, 4, 5, 6, 7, 8, // h
        0, 1, 2, 3, 4, 3, 4, 5, 6, 7, 8, // w
      ];
      expect(got, equals(expected));
    });

    test('rect_2x4_grid: 8-token image span', () {
      final inputIds = <int>[
        5,
        101305,
        for (var i = 0; i < 8; i++) _imageTokenId,
        101306,
        6, 7,
      ];
      final got = computeMRopePositionIds(
        inputIds: inputIds,
        imageGridThw: (1, 4, 8),
        imageTokenId: _imageTokenId,
      );
      const expected = <double>[
        0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 6, 7, 8, // t
        0, 1, 2, 2, 2, 2, 3, 3, 3, 3, 6, 7, 8, // h
        0, 1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 7, 8, // w
      ];
      expect(got, equals(expected));
    });

    test('square_3x3_no_post: 9-token image span, no trailing text', () {
      final inputIds = <int>[
        1, 2, 3,
        101305,
        for (var i = 0; i < 9; i++) _imageTokenId,
        101306,
      ];
      final got = computeMRopePositionIds(
        inputIds: inputIds,
        imageGridThw: (1, 6, 6),
        imageTokenId: _imageTokenId,
      );
      const expected = <double>[
        0, 1, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 7, // t
        0, 1, 2, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, // h
        0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 7, // w
      ];
      expect(got, equals(expected));
    });

    test('text_only: 1-D arange replicated across 3 streams', () {
      final got = computeMRopePositionIds(
        inputIds: const [100, 200, 300, 400],
        imageGridThw: (1, 0, 0),
        imageTokenId: _imageTokenId,
      );
      const expected = <double>[
        0, 1, 2, 3,
        0, 1, 2, 3,
        0, 1, 2, 3,
      ];
      expect(got, equals(expected));
    });
  });

  group('computeMRopePositionIds — error handling', () {
    test('mismatched image-token count throws ArgumentError', () {
      // grid (1,4,4) requires 4 image placeholders; we provide 3.
      final inputIds = <int>[
        101305,
        _imageTokenId, _imageTokenId, _imageTokenId,
        101306,
      ];
      expect(
        () => computeMRopePositionIds(
          inputIds: inputIds,
          imageGridThw: (1, 4, 4),
          imageTokenId: _imageTokenId,
        ),
        throwsArgumentError,
      );
    });
  });

  group('computeDecodePositionIds', () {
    test('advances all 3 streams by step+1 from anchor', () {
      // Anchor (5, 6, 7) — typical "last position" after a 3x3 image.
      final step0 = computeDecodePositionIds(
        newTokenIndex: 0,
        anchorPosition: (5, 6, 7),
      );
      expect(step0, equals(<double>[6, 7, 8]));

      final step1 = computeDecodePositionIds(
        newTokenIndex: 1,
        anchorPosition: (5, 6, 7),
      );
      expect(step1, equals(<double>[7, 8, 9]));

      final step5 = computeDecodePositionIds(
        newTokenIndex: 5,
        anchorPosition: (5, 6, 7),
      );
      expect(step5, equals(<double>[11, 12, 13]));
    });
  });

  group('lastPositionTriple', () {
    test('extracts (t, h, w) from the final slot of a flat buffer', () {
      // Reuse the tiny_2x2_grid golden — last token positions = (8, 8, 8).
      final inputIds = <int>[
        10, 11, 101305,
        _imageTokenId, _imageTokenId, _imageTokenId, _imageTokenId,
        101306, 20, 21, 22,
      ];
      final flat = computeMRopePositionIds(
        inputIds: inputIds,
        imageGridThw: (1, 4, 4),
        imageTokenId: _imageTokenId,
      );
      expect(lastPositionTriple(flat, inputIds.length), equals((8, 8, 8)));
    });
  });
}
