name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
